version: "3.8"

services:
  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=dbsalon
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
